<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Privacy Policy | Arise Education Point</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- Arise Theme -->
  <link rel="stylesheet" href="{{ asset('public/assets/school/css/arise-theme.css') }}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css">

  <!-- Optional: Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

  <style>
    body {
      font-size: 0.95rem;
    }
    .content-wrapper {
      min-height: 100vh;
    }
    .policy-section h3 {
      margin-top: 1.5rem;
    }
    .policy-section p,
    .policy-section li {
      line-height: 1.6;
    }
  </style>
</head>
<body class="hold-transition layout-top-nav">

<div class="wrapper">

  <!-- Top Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
    <div class="container">
      <a href="#" class="navbar-brand">
        <span class="brand-text font-weight-light">
          Arise Education Point
        </span>
      </a>
    </div>
  </nav>

  <!-- Content Wrapper -->
  <div class="content-wrapper">

    <!-- Content Header -->
    <section class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Privacy Policy</h1>
          </div>
          <div class="col-sm-6 text-right">
            <small class="text-muted">
              Last updated: 10 December 2025
            </small>
          </div>
        </div>
      </div>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container">
        <div class="card">
          <div class="card-body policy-section">

            <p>
              This Privacy Policy describes how Arise Education Point
              (“we”, “our”, or “us”) collects, uses, and protects your information when
              you use our mobile applications and web services (collectively, the “Service”).
              Our apps and web platforms are developed and maintained by
              <strong>Arise Education Point</strong>.
            </p>

            <p>
              By installing, accessing, or using our Android application (distributed via Google Play Store)
              or our website, you agree to the collection and use of information in accordance
              with this Privacy Policy.
            </p>

            <h3>1. Definitions</h3>
            <ul>
              <li><strong>Service</strong>: The Android application and website of Arise Education Point.</li>
              <li><strong>Organization</strong>: Arise Education Point.</li>
              <li><strong>Developer</strong>: Arise Education Point.</li>
              <li><strong>Personal Data</strong>: Any information that can be used to identify an individual.</li>
              <li><strong>Usage Data</strong>: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            </ul>

            <h3>2. Information We Collect</h3>

            <h5>a) Personal Data</h5>
            <p>We may collect the following information:</p>
            <ul>
              <li>Full name</li>
              <li>Email address</li>
              <li>Mobile phone number</li>
              <li>Class, course, batch details</li>
              <li>Parent/guardian name and contact details</li>
              <li>Login username or student ID</li>
            </ul>

            <h5>b) Usage Data</h5>
            <p>We may automatically collect:</p>
            <ul>
              <li>Device type and model</li>
              <li>Operating system version</li>
              <li>App version</li>
              <li>IP address</li>
              <li>Pages/screens visited</li>
              <li>Crash logs</li>
            </ul>

            <h5>c) Permissions</h5>
            <p>The app may request:</p>
            <ul>
              <li><strong>Storage</strong></li>
              <li><strong>Camera</strong></li>
              <li><strong>Internet Access</strong></li>
              <li><strong>Notifications</strong></li>
            </ul>

            <h3>3. How We Use Your Information</h3>
            <ul>
              <li>Manage student accounts</li>
              <li>Provide academic services</li>
              <li>Send notifications and updates</li>
              <li>Improve app performance</li>
              <li>Prevent fraud or misuse</li>
              <li>Comply with legal obligations</li>
            </ul>

            <h3>4. Children’s Privacy</h3>
            <p>
              Our Service may be used by minors under the supervision of parents/guardians or the institution.
              We do not knowingly collect data without proper authorization.
            </p>

            <h3>5. Data Sharing</h3>
            <ul>
              <li>With authorized institute staff</li>
              <li>With service providers (hosting, analytics, notification services)</li>
              <li>For legal compliance</li>
            </ul>

            <h3>6. Third-Party Services</h3>
            <ul>
              <li>Google Play Services</li>
              <li>Firebase</li>
              <li>Crashlytics</li>
            </ul>

            <h3>7. Data Security & Retention</h3>
            <p>
              We use appropriate security measures. However, no online system is 100% secure.
              Data is retained only as long as necessary.
            </p>

            <h3>8. Your Rights</h3>
            <ul>
              <li>Request access to your data</li>
              <li>Request corrections or updates</li>
              <li>Request deletion (where allowed)</li>
            </ul>

            <h3>9. Cookies</h3>
            <p>
              Our website may use cookies to enhance user experience. You may disable them if desired.
            </p>

            <h3>10. Changes to This Policy</h3>
            <p>
              We may update this Privacy Policy from time to time. Changes will be posted on this page.
            </p>

            <h3>11. Contact Us</h3>
            <p>If you have questions or requests, please contact:</p>

            <ul>
              <li><strong>Organization:</strong> Arise Education Point</li>
              <li><strong>Email:</strong> teamarise57@gmail.com</li>
              <li><strong>Phone:</strong> 9694343442</li>
              <li><strong>Address:</strong> Behind Tehsil, Modern Happy School, Dholi Mandi, Chomu, Jaipur, Rajasthan 303702</li>
            </ul>

          </div>
        </div>
      </div>
    </section>

  </div>

  <!-- Footer -->
  <footer class="main-footer text-sm">
    <div class="container">
      <div class="float-right d-none d-sm-inline">
        App &amp; Web by Arise Education Point
      </div>
      <strong>
        &copy; <span id="year"></span> Arise Education Point.
      </strong> All rights reserved.
    </div>
  </footer>
</div>

<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('public/assets/school/js/arise-theme.js') }}"></script>
<script>
  // Auto-set current year
  document.getElementById('year').textContent = new Date().getFullYear();
</script>
</body>
</html>
