@php
    $getUser = Helper::getUser();
    $totalComplaints = (int) ($complaintCounts->total_count ?? 0);
    $activeComplaints = (int) ($complaintCounts->active_count ?? 0);
    $awaitingComplaints = (int) ($complaintCounts->awaiting_count ?? 0);
    $resolvedComplaints = (int) ($complaintCounts->resolved_count ?? 0);
    $categoryIcons = ['academic'=>'bi-mortarboard','fees'=>'bi-wallet2','attendance'=>'bi-calendar2-check','transport'=>'bi-bus-front','facility'=>'bi-buildings','staff'=>'bi-person-badge','technical'=>'bi-laptop','other'=>'bi-chat-square-text'];
@endphp

@extends('student_login.layout.app')
@section('title','Help & Support')
@section('page_title','HELP & SUPPORT')
@section('page_sub',Session::get('first_name').' · '.($getUser['ClassTypes']['name'] ?? 'Student'))

@section('content')
<style>
  .stu-support{--sp-primary:#3156d3;--sp-success:#139466;--sp-warning:#d78a00;--sp-danger:#d14d4d;min-height:calc(100vh - 126px);padding:14px 14px 108px;background:var(--stu-page,#f3f6fb);color:var(--stu-text,#253858)}
  .sp-hero{position:relative;overflow:hidden;padding:18px;border-radius:20px;background:linear-gradient(135deg,#3156d3,#263f9e);color:#fff;box-shadow:0 12px 30px rgba(32,61,154,.22)}.sp-hero:before,.sp-hero:after{content:"";position:absolute;border-radius:50%;border:25px solid rgba(255,255,255,.06)}.sp-hero:before{width:150px;height:150px;right:-55px;top:-72px}.sp-hero:after{width:90px;height:90px;left:-50px;bottom:-64px}.sp-hero-top{position:relative;z-index:1;display:flex;align-items:center;gap:13px}.sp-hero-icon{width:50px;height:50px;flex:0 0 50px;display:grid;place-items:center;border-radius:15px;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.17);font-size:22px}.sp-hero-copy{min-width:0;flex:1}.sp-hero-copy span{display:block;font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;opacity:.72}.sp-hero-copy h1{font-size:20px;font-weight:750;margin:2px 0}.sp-hero-copy p{font-size:10px;line-height:1.4;margin:0;opacity:.8}.sp-new-button{position:relative;z-index:1;min-height:44px;display:flex;align-items:center;justify-content:center;gap:7px;margin-top:15px;border-radius:13px;background:#fff;color:var(--sp-primary);font-size:11px;font-weight:750;text-decoration:none;box-shadow:0 7px 18px rgba(20,34,80,.18)}.sp-hero-stats{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,1fr);margin-top:14px;padding-top:12px;border-top:1px solid rgba(255,255,255,.15)}.sp-hero-stat{text-align:center;border-right:1px solid rgba(255,255,255,.15)}.sp-hero-stat:last-child{border:0}.sp-hero-stat strong{display:block;font-size:16px}.sp-hero-stat span{font-size:8px;text-transform:uppercase;letter-spacing:.06em;opacity:.7}
  .sp-filter-wrap{position:sticky;z-index:5;top:74px;margin:12px -14px 0;padding:6px 14px 8px;background:linear-gradient(var(--stu-page,#f3f6fb) 76%,transparent)}.sp-filters{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none}.sp-filters::-webkit-scrollbar{display:none}.sp-filter{flex:0 0 auto;min-height:38px;display:inline-flex;align-items:center;gap:6px;padding:7px 11px;border:1px solid var(--stu-border,#edf0f6);border-radius:12px;background:var(--stu-surface,#fff);color:var(--stu-muted,#98a2b3);font-size:10px;font-weight:650;text-decoration:none}.sp-filter b{min-width:18px;height:18px;display:grid;place-items:center;padding:0 5px;border-radius:8px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary);font-size:8px}.sp-filter.active{border-color:transparent;background:linear-gradient(135deg,#3156d3,#2746b0);color:#fff;box-shadow:0 6px 14px rgba(49,86,211,.18)}.sp-filter.active b{background:rgba(255,255,255,.18);color:#fff}
  .sp-section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:10px;margin:11px 2px 9px}.sp-section-head h2{font-size:15px;font-weight:750;margin:0}.sp-section-head p{font-size:10px;color:var(--stu-muted,#98a2b3);margin:2px 0 0}.sp-result-count{padding:5px 8px;border-radius:9px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary);font-size:8px;font-weight:700}
  .sp-card{position:relative;overflow:hidden;display:block;margin-bottom:10px;padding:13px 12px 12px 15px;border:1px solid var(--stu-border,#edf0f6);border-radius:17px;background:var(--stu-surface,#fff);color:inherit;text-decoration:none;box-shadow:var(--stu-shadow,0 7px 24px rgba(42,55,92,.06));transition:transform .16s}.sp-card:active{transform:scale(.985)}.sp-card:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--sp-primary)}.sp-card.status-awaiting_user:before{background:var(--sp-warning)}.sp-card.status-resolved:before,.sp-card.status-closed:before{background:var(--sp-success)}.sp-card-top{display:flex;align-items:flex-start;gap:10px}.sp-category-icon{width:39px;height:39px;flex:0 0 39px;display:grid;place-items:center;border-radius:12px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary);font-size:16px}.sp-card-main{min-width:0;flex:1}.sp-ticket{display:block;margin-bottom:3px;color:var(--stu-muted,#98a2b3);font-size:8px;font-weight:650;letter-spacing:.05em}.sp-card-main h3{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;margin:0;font-size:13px;font-weight:720;line-height:1.35}.sp-status{flex:0 0 auto;max-width:90px;padding:5px 7px;border-radius:9px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary);font-size:8px;font-weight:700;line-height:1.2;text-align:center}.sp-status.awaiting_user{background:#fff4dc;color:var(--sp-warning)}.sp-status.resolved,.sp-status.closed{background:#e4f8ef;color:var(--sp-success)}.sp-card-meta{display:flex;align-items:center;gap:8px 11px;flex-wrap:wrap;margin:11px 0 0 49px;padding-top:10px;border-top:1px solid var(--stu-border,#edf0f6);color:var(--stu-muted,#98a2b3);font-size:8px}.sp-card-meta span{display:flex;align-items:center;gap:4px}.sp-priority{padding:4px 6px;border-radius:7px;background:#edf1f5;color:#657186;font-weight:700}.sp-priority.high,.sp-priority.urgent{background:#ffeceb;color:var(--sp-danger)}.sp-priority.medium{background:#fff4dc;color:var(--sp-warning)}.sp-arrow{margin-left:auto;width:25px;height:25px;display:grid!important;place-items:center!important;border-radius:8px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary)}
  .sp-empty{padding:39px 20px;text-align:center;border:1px solid var(--stu-border,#edf0f6);border-radius:18px;background:var(--stu-surface,#fff)}.sp-empty-icon{width:60px;height:60px;display:grid;place-items:center;margin:0 auto 12px;border-radius:18px;background:var(--stu-primary-soft,#e8eeff);color:var(--sp-primary);font-size:25px}.sp-empty h3{font-size:14px;margin:0 0 5px}.sp-empty p{max-width:285px;margin:0 auto 14px;color:var(--stu-muted,#98a2b3);font-size:10px;line-height:1.5}.sp-empty a{min-height:42px;display:inline-flex;align-items:center;gap:6px;padding:9px 14px;border-radius:11px;background:var(--sp-primary);color:#fff;font-size:10px;font-weight:700;text-decoration:none}.sp-pagination{margin-top:15px}.sp-pagination .pagination{justify-content:center;gap:4px;flex-wrap:wrap}.sp-pagination .page-link{min-width:34px;height:34px;display:grid;place-items:center;padding:0;border-radius:10px!important;border-color:var(--stu-border,#edf0f6);background:var(--stu-surface,#fff);color:var(--sp-primary);font-size:10px}.sp-pagination .page-item.active .page-link{border-color:var(--sp-primary);background:var(--sp-primary);color:#fff}
  [data-theme=dark] .stu-support{--stu-page:#0f1728;--stu-surface:#182337;--stu-text:#f2f5fb;--stu-muted:#9da9bd;--stu-border:#29364c;--stu-primary-soft:#24365f}[data-theme=dark] .sp-priority{background:#263248;color:#b4bfd0}[data-theme=dark] .sp-priority.medium,[data-theme=dark] .sp-status.awaiting_user{background:#3d321c;color:#f0bd62}[data-theme=dark] .sp-priority.high,[data-theme=dark] .sp-priority.urgent{background:#3a2429;color:#ff9292}[data-theme=dark] .sp-status.resolved,[data-theme=dark] .sp-status.closed{background:#193c34;color:#76dcb4}
</style>

<section class="stu-support">
  <div class="sp-hero">
    <div class="sp-hero-top"><div class="sp-hero-icon"><i class="bi bi-headset"></i></div><div class="sp-hero-copy"><span>Student help desk</span><h1>How can we help?</h1><p>Raise a concern and track every response from the school team.</p></div></div>
    <a href="{{ url('student-complaints/create') }}" class="sp-new-button"><i class="bi bi-plus-circle"></i>Raise a new complaint</a>
    <div class="sp-hero-stats"><div class="sp-hero-stat"><strong>{{ $totalComplaints }}</strong><span>Total</span></div><div class="sp-hero-stat"><strong>{{ $activeComplaints }}</strong><span>Active</span></div><div class="sp-hero-stat"><strong>{{ $resolvedComplaints }}</strong><span>Resolved</span></div></div>
  </div>

  <nav class="sp-filter-wrap" aria-label="Filter complaints"><div class="sp-filters">
    @foreach(['all'=>['All','bi-grid',$totalComplaints], 'active'=>['Active','bi-hourglass-split',$activeComplaints], 'awaiting'=>['Your reply','bi-reply',$awaitingComplaints], 'resolved'=>['Resolved','bi-check2-circle',$resolvedComplaints]] as $key=>$item)
      <a href="{{ url('student-complaints?status='.$key) }}" class="sp-filter {{ $filter===$key?'active':'' }}" @if($filter===$key) aria-current="page" @endif><i class="bi {{ $item[1] }}"></i>{{ $item[0] }}<b>{{ $item[2] }}</b></a>
    @endforeach
  </div></nav>

  <div class="sp-section-head"><div><h2>{{ ['all'=>'All complaints','active'=>'Active complaints','awaiting'=>'Waiting for your reply','resolved'=>'Resolved complaints'][$filter] }}</h2><p>Latest conversations appear first</p></div><span class="sp-result-count">{{ $complaints->total() }} FOUND</span></div>

  <div class="sp-list">
    @forelse($complaints as $complaint)
      @php $statusLabel=\App\Models\SupportComplaint::STATUSES[$complaint->status]??ucfirst(str_replace('_',' ',$complaint->status)); $categoryLabel=\App\Models\SupportComplaint::CATEGORIES[$complaint->category]??ucfirst($complaint->category); @endphp
      <a class="sp-card status-{{ $complaint->status }}" href="{{ url('student-complaints/'.$complaint->id) }}">
        <span class="sp-card-top"><span class="sp-category-icon"><i class="bi {{ $categoryIcons[$complaint->category] ?? 'bi-chat-square-text' }}"></i></span><span class="sp-card-main"><span class="sp-ticket">{{ $complaint->ticket_no }}</span><h3>{{ $complaint->subject }}</h3></span><span class="sp-status {{ $complaint->status }}">{{ $statusLabel }}</span></span>
        <span class="sp-card-meta"><span><i class="bi bi-folder2"></i>{{ $categoryLabel }}</span><span><i class="bi bi-chat-dots"></i>{{ $complaint->replies_count }} {{ \Illuminate\Support\Str::plural('message',$complaint->replies_count) }}</span><span class="sp-priority {{ $complaint->priority }}">{{ ucfirst($complaint->priority) }}</span><span><i class="bi bi-clock"></i>{{ optional($complaint->last_replied_at)->diffForHumans() ?: 'No reply yet' }}</span><i class="bi bi-chevron-right sp-arrow"></i></span>
      </a>
    @empty
      <div class="sp-empty"><div class="sp-empty-icon"><i class="bi bi-chat-square-heart"></i></div><h3>{{ $filter==='all'?'No complaints submitted':'Nothing in this section' }}</h3><p>{{ $filter==='all'?'If you need help, raise a complaint and the school team will respond here.':'Complaints matching this status will appear here.' }}</p>@if($filter==='all')<a href="{{ url('student-complaints/create') }}"><i class="bi bi-plus-lg"></i>Raise complaint</a>@endif</div>
    @endforelse
  </div>
  @if($complaints->hasPages())<div class="sp-pagination">{{ $complaints->links() }}</div>@endif
</section>
@endsection
